/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * This file is part of paged (https://paged.media) and is additionally
 * available under the Paged Media Enterprise License (PMEL). Full
 * copyright and license information is available in LICENSE.md which is
 * distributed with this source code.
 *
 *  @copyright  Copyright (c) And The Next GmbH
 *  @license    MPL-2.0 OR Paged Media Enterprise License (PMEL)
 */

//! Dispatch codegen (spec §7/§12.2). Reads every
//! `../registry/functions/*.yaml` and emits `$OUT_DIR/dispatch.rs`: one
//! match arm per function row, keyed by the same `id`-sorted [`FuncId`]
//! index that `sheet-core/build.rs` assigns (the two builders MUST mirror
//! each other's sort so the indices agree — **FuncId parity**). For an
//! `implemented` row the arm range-checks the arity, then calls
//! `crate::families::<rust>`; a `planned` row returns `#NAME?` (unimplemented
//! but registered); an arity violation returns `#VALUE!`. No registry row →
//! no arm → uncallable by construction.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Arity {
    min: u8,
    #[serde(default)]
    max: Option<u8>,
}

#[derive(Debug, Deserialize)]
struct FnRow {
    id: String,
    name: String,
    arity: Arity,
    /// The kernel symbol under `sheet_fn::families::` (e.g. `math::sum`).
    /// Only consulted for `implemented` rows.
    #[serde(default)]
    rust: String,
    #[serde(default)]
    status: String,
    // Unknown fields (family, volatility, provenance, tests, …) ignored.
}

fn main() {
    // Re-run when any registry function YAML changes (same trigger set as
    // sheet-core/build.rs so the two regenerate in lockstep).
    println!("cargo:rerun-if-changed=../registry/functions");
    println!("cargo:rerun-if-changed=build.rs");

    let dir = Path::new("../registry/functions");
    let mut rows: Vec<FnRow> = Vec::new();

    let mut entries: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("sheet-fn build.rs: cannot read {dir:?}: {e}"))
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().map(|x| x == "yaml").unwrap_or(false))
        .collect();
    entries.sort();

    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let text = fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("sheet-fn build.rs: read {path:?}: {e}"));
        let parsed: Vec<FnRow> = serde_yaml::from_str(&text)
            .unwrap_or_else(|e| panic!("sheet-fn build.rs: parse {path:?}: {e}"));
        rows.extend(parsed);
    }

    // ---- Validation: an implemented row MUST name a kernel symbol. ----
    let mut seen_id: BTreeMap<&str, ()> = BTreeMap::new();
    for r in &rows {
        if seen_id.insert(r.id.as_str(), ()).is_some() {
            panic!("sheet-fn build.rs: duplicate function id {:?}", r.id);
        }
        let implemented = r.status.eq_ignore_ascii_case("implemented");
        if implemented && r.rust.trim().is_empty() {
            panic!(
                "sheet-fn build.rs: function {} is implemented but has no `rust` symbol",
                r.id
            );
        }
        if let Some(max) = r.arity.max {
            if r.arity.min > max {
                panic!(
                    "sheet-fn build.rs: function {} has arity min {} > max {}",
                    r.id, r.arity.min, max
                );
            }
        }
    }

    // ---- Sort by id → FuncId == sorted index (mirrors sheet-core). ----
    rows.sort_by(|a, b| a.id.cmp(&b.id));

    // ---- Emit the dispatch function. ----
    let mut out = String::new();
    out.push_str(
        "// @generated by sheet-fn/build.rs from ../registry/functions/*.yaml — DO NOT EDIT.\n\n",
    );

    out.push_str(
        "/// Registry-driven dispatch (spec §7). `id` is a sheet-core\n\
         /// [`sheet_core::FuncId`]; the match arm is generated from the same\n\
         /// `id`-sorted registry, so the index here is the index there\n\
         /// (FuncId parity). An `implemented` row arity-checks then calls its\n\
         /// kernel; a `planned` row returns `#NAME?`; an arity violation\n\
         /// returns `#VALUE!`. There is no fallthrough table — an out-of-range\n\
         /// id is an internal invariant break and returns `#NAME?`.\n\
         // Generated guards are uniform (`len < min`/`len > max` straight from\n\
         // the YAML), so the zero/one/u8::MAX special cases clippy wants are\n\
         // noise here — blanket-allow on the generated fn only.\n\
         #[allow(clippy::len_zero, clippy::absurd_extreme_comparisons, unused_comparisons)]\n\
         pub fn dispatch(\n\
         \x20   id: sheet_core::FuncId,\n\
         \x20   args: &[crate::arg::Arg],\n\
         \x20   ctx: &crate::ctx::EvalCtx,\n\
         ) -> sheet_core::CellValue {\n\
         \x20   use sheet_core::value::{CellError, CellValue};\n\
         \x20   // `args`/`ctx` are bound for kernels; both are unused only in\n\
         \x20   // the degenerate all-`planned` build, hence the discards.\n\
         \x20   let _ = (args, ctx);\n\
         \x20   match id.0 {\n",
    );

    for (i, r) in rows.iter().enumerate() {
        let implemented = r.status.eq_ignore_ascii_case("implemented");
        if implemented {
            // `rust: math::sum` → `crate::families::math::sum`.
            let path = format!("crate::families::{}", r.rust.trim());
            // Arity guard: len < min || (max.is_some() && len > max).
            let max_guard = match r.arity.max {
                Some(m) => format!(" || args.len() > {m}"),
                None => String::new(),
            };
            writeln!(
                out,
                "        {i} => {{ // {name}\n\
                 \x20           if args.len() < {min}{max_guard} {{\n\
                 \x20               return CellValue::Error(CellError::Value);\n\
                 \x20           }}\n\
                 \x20           {path}(args, ctx)\n\
                 \x20       }}",
                i = i,
                name = r.name,
                min = r.arity.min,
                max_guard = max_guard,
                path = path,
            )
            .unwrap();
        } else {
            // Registered but unimplemented: callable name, no kernel → #NAME?.
            writeln!(
                out,
                "        {i} => CellValue::Error(CellError::Name), // {name} (planned)",
                i = i,
                name = r.name,
            )
            .unwrap();
        }
    }

    out.push_str(
        "        _ => CellValue::Error(CellError::Name),\n\
         \x20   }\n\
         }\n",
    );

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("dispatch.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("sheet-fn build.rs: write {dest:?}: {e}"));
}
