/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * This file is part of paged (https://paged.media) and is additionally
 * available under the Paged Media Enterprise License (PMEL). Full
 * copyright and license information is available in LICENSE.md which is
 * distributed with this source code.
 *
 *  @copyright  Copyright (c) And The Next GmbH
 *  @license    MPL-2.0 OR Paged Media Enterprise License (PMEL)
 */

//! Registry codegen (spec §7/§12.2). Reads every
//! `../registry/functions/*.yaml`, validates the rows, sorts them by `id`
//! (so `FuncId` is stable against YAML reordering), and emits the static
//! `FUNC_META` table + the `lookup_func`/`meta` accessors into
//! `$OUT_DIR/funcs.rs`. An unregistered function has no row, hence no
//! `FuncId`, hence no dispatch — uncallable by construction.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Arity {
    min: u8,
    #[serde(default)]
    max: Option<u8>,
}

#[derive(Debug, Deserialize)]
struct FnRow {
    id: String,
    name: String,
    #[serde(default)]
    family: String,
    arity: Arity,
    #[serde(default)]
    volatility: String,
    #[serde(default)]
    range_aware: bool,
    #[serde(default)]
    ref_args: bool,
    /// True for dynamic-array kernels (M1 array track) — `dispatch_rich`
    /// calls them directly; the scalar `dispatch` door returns `#VALUE!`.
    #[serde(default)]
    returns_array: bool,
    #[serde(default)]
    status: String,
    // Other fields (rust, provenance, tests) are intentionally ignored
    // here; serde_yaml allows unknown fields (no deny_unknown_fields).
}

fn main() {
    // Re-run when any registry function YAML changes.
    println!("cargo:rerun-if-changed=../registry/functions");
    println!("cargo:rerun-if-changed=build.rs");

    let dir = Path::new("../registry/functions");
    let mut rows: Vec<FnRow> = Vec::new();

    let mut entries: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("sheet-core build.rs: cannot read {dir:?}: {e}"))
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().map(|x| x == "yaml").unwrap_or(false))
        .collect();
    entries.sort();

    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let text = fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("sheet-core build.rs: read {path:?}: {e}"));
        let parsed: Vec<FnRow> = serde_yaml::from_str(&text)
            .unwrap_or_else(|e| panic!("sheet-core build.rs: parse {path:?}: {e}"));
        rows.extend(parsed);
    }

    // ---- Validation (panic at build time on any contract violation) ----
    if rows.len() > u16::MAX as usize {
        panic!(
            "sheet-core build.rs: {} function rows exceeds u16::MAX FuncId space",
            rows.len()
        );
    }

    let name_re_ok = |name: &str| -> bool {
        // ^[A-Z][A-Z0-9.]*$
        let mut bytes = name.bytes();
        match bytes.next() {
            Some(b) if b.is_ascii_uppercase() => {}
            _ => return false,
        }
        bytes.all(|b| b.is_ascii_uppercase() || b.is_ascii_digit() || b == b'.')
    };

    let mut seen_id: BTreeMap<&str, ()> = BTreeMap::new();
    let mut seen_name: BTreeMap<&str, ()> = BTreeMap::new();
    for r in &rows {
        if !name_re_ok(&r.name) {
            panic!(
                "sheet-core build.rs: function name {:?} (id {}) must match ^[A-Z][A-Z0-9.]*$",
                r.name, r.id
            );
        }
        if let Some(max) = r.arity.max {
            if r.arity.min > max {
                panic!(
                    "sheet-core build.rs: function {} has arity min {} > max {}",
                    r.id, r.arity.min, max
                );
            }
        }
        if seen_id.insert(r.id.as_str(), ()).is_some() {
            panic!("sheet-core build.rs: duplicate function id {:?}", r.id);
        }
        if seen_name.insert(r.name.as_str(), ()).is_some() {
            panic!("sheet-core build.rs: duplicate function name {:?}", r.name);
        }
    }

    // ---- Sort by id → FuncId == sorted index (stable ordering) ----
    rows.sort_by(|a, b| a.id.cmp(&b.id));

    // ---- Emit ----
    let mut out = String::new();
    out.push_str(
        "// @generated by sheet-core/build.rs from ../registry/functions/*.yaml — DO NOT EDIT.\n\n",
    );

    out.push_str(
        "/// Static metadata for one registered function (spec §7).\n\
         #[derive(Debug)]\n\
         pub struct FuncMeta {\n\
         \x20   pub id: &'static str,\n\
         \x20   pub name: &'static str,\n\
         \x20   pub family: &'static str,\n\
         \x20   pub min_args: u8,\n\
         \x20   pub max_args: Option<u8>,\n\
         \x20   pub volatile: bool,\n\
         \x20   pub range_aware: bool,\n\
         \x20   pub ref_args: bool,\n\
         \x20   pub returns_array: bool,\n\
         \x20   pub implemented: bool,\n\
         }\n\n",
    );

    out.push_str("/// All registered functions, sorted by `id` (index == FuncId).\n");
    out.push_str("pub const FUNC_META: &[FuncMeta] = &[\n");
    for r in &rows {
        let volatile = r.volatility.eq_ignore_ascii_case("volatile");
        let implemented = r.status.eq_ignore_ascii_case("implemented");
        let max = match r.arity.max {
            Some(m) => format!("Some({m})"),
            None => "None".to_string(),
        };
        writeln!(
            out,
            "    FuncMeta {{ id: {:?}, name: {:?}, family: {:?}, min_args: {}, max_args: {}, volatile: {}, range_aware: {}, ref_args: {}, returns_array: {}, implemented: {} }},",
            r.id, r.name, r.family, r.arity.min, max, volatile, r.range_aware, r.ref_args, r.returns_array, implemented
        )
        .unwrap();
    }
    out.push_str("];\n\n");

    // lookup_func: case-insensitive (query is uppercased), match over UPPER names.
    out.push_str(
        "/// Case-insensitive name → `FuncId`. Returns `None` for any\n\
         /// unregistered name (uncallable by construction).\n\
         pub fn lookup_func(name: &str) -> Option<crate::ast::FuncId> {\n\
         \x20   let upper = name.to_ascii_uppercase();\n\
         \x20   match upper.as_str() {\n",
    );
    for (i, r) in rows.iter().enumerate() {
        writeln!(
            out,
            "        {:?} => Some(crate::ast::FuncId({})),",
            r.name, i
        )
        .unwrap();
    }
    out.push_str(
        "        _ => None,\n\
         \x20   }\n\
         }\n\n",
    );

    out.push_str(
        "/// Resolve a `FuncId` to its metadata. Panics on an out-of-range\n\
         /// id — an internal invariant (ids only come from `lookup_func`).\n\
         pub fn meta(id: crate::ast::FuncId) -> &'static FuncMeta {\n\
         \x20   &FUNC_META[id.0 as usize]\n\
         }\n",
    );

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("funcs.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("sheet-core build.rs: write {dest:?}: {e}"));
}
